const API_URL='https://n8n-pi.taild8d05f.ts.net/webhook/lista-zakupow-v2';
const $=id=>document.getElementById(id);
const state={items:[],archive:[],recognized:[],busy:false,timer:null,started:0,installPrompt:null};
const els={offline:$('offline'),processing:$('processing'),processingTitle:$('processingTitle'),processingMsg:$('processingMsg'),processingTime:$('processingTime'),installBtn:$('installBtn'),tabs:[...document.querySelectorAll('.tab')],views:[...document.querySelectorAll('.view')],listItems:$('listItems'),listCount:$('listCount'),textInput:$('textInput'),recognizeTextBtn:$('recognizeTextBtn'),photoInput:$('photoInput'),recognitionPanel:$('recognitionPanel'),recognizedItems:$('recognizedItems'),cancelRecognitionBtn:$('cancelRecognitionBtn'),saveRecognitionBtn:$('saveRecognitionBtn'),shopItems:$('shopItems'),finishBtn:$('finishBtn'),archiveItems:$('archiveItems'),archiveDetail:$('archiveDetail'),toast:$('toast')};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function startProcessing(title,msg){state.busy=true;els.processingTitle.textContent=title;els.processingMsg.textContent=msg;els.processingTime.textContent='0 s';els.processing.classList.remove('hidden');state.started=Date.now();clearInterval(state.timer);state.timer=setInterval(()=>{els.processingTime.textContent=Math.floor((Date.now()-state.started)/1000)+' s';},1000)}
function stopProcessing(){state.busy=false;clearInterval(state.timer);state.timer=null;els.processing.classList.add('hidden')}
let toastTimer=null;function toast(msg){clearTimeout(toastTimer);els.toast.textContent=msg;els.toast.classList.remove('hidden');toastTimer=setTimeout(()=>els.toast.classList.add('hidden'),2600)}
async function api(action,fields={},file=null){const fd=new FormData();fd.append('action',action);Object.entries(fields).forEach(([k,v])=>fd.append(k,String(v??'')));if(file)fd.append('data',file,file.name||'photo.jpg');let res;try{res=await fetch(API_URL,{method:'POST',body:fd,cache:'no-store'})}catch(e){throw new Error('Brak połączenia z serwerem.')}let data;try{data=await res.json()}catch(e){throw new Error('Serwer zwrócił nieprawidłową odpowiedź.')}if(!res.ok)throw new Error(data?.message||data?.error||('HTTP '+res.status));return data}
function switchView(name){els.tabs.forEach(t=>t.classList.toggle('active',t.dataset.view===name));els.views.forEach(v=>v.classList.toggle('active',v.id==='view-'+name));window.scrollTo(0,0);if(name==='list')loadList();if(name==='shop')loadList();if(name==='archive')loadArchive()}
function formatDate(s){if(!s)return '';const d=new Date(s);return Number.isNaN(d.getTime())?String(s):new Intl.DateTimeFormat('pl-PL',{dateStyle:'short',timeStyle:'short'}).format(d)}
async function loadList(){try{const d=await api('list');if(!d.success)throw new Error(d.message||d.error||'Nie udało się pobrać listy.');state.items=Array.isArray(d.items)?d.items:[];renderList();renderShop()}catch(e){toast(e.message)}}
function renderList(){els.listCount.textContent=state.items.length?`${state.items.length} pozycji`:'Lista jest pusta';els.listItems.innerHTML=state.items.length?state.items.map(x=>`<div class="item"><div class="item-main"><strong>${esc(x.product)}</strong><small>${x.checked?'✓ w koszyku':'dodano '+esc(formatDate(x.addedAt))}</small></div><button class="delete-btn" type="button" data-delete="${esc(x.itemId)}">Usuń</button></div>`).join(''):'<div class="empty">Lista zakupów jest pusta.</div>'}
async function deleteItem(id){const row=state.items.find(x=>x.itemId===id);if(!row)return;if(!confirm(`Usunąć „${row.product}” z listy?`))return;startProcessing('Usuwam produkt','Aktualizuję listę zakupów…');try{const d=await api('delete_item',{itemId:id});if(!d.success)throw new Error(d.message||d.error||'Nie udało się usunąć produktu.');await loadList();stopProcessing();toast('Produkt usunięty.')}catch(e){stopProcessing();toast(e.message)}}
function setRecognized(products){state.recognized=(products||[]).map(x=>String(x).trim()).filter(Boolean);renderRecognized();els.recognitionPanel.classList.toggle('hidden',!state.recognized.length)}
function renderRecognized(){els.recognizedItems.innerHTML=state.recognized.map((x,i)=>`<div class="recognized-row"><span>${esc(x)}</span><button class="delete-btn" type="button" data-remove-recognized="${i}">Usuń</button></div>`).join('');els.saveRecognitionBtn.disabled=!state.recognized.length}
async function recognizeText(){const text=els.textInput.value.trim();if(!text){toast('Wpisz produkty.');return}startProcessing('Rozpoznaję produkty','Porządkuję wpis i dzielę go na pozycje…');try{const d=await api('recognize_text',{text});if(!d.success)throw new Error(d.message||d.error||'Nie rozpoznano produktów.');setRecognized(d.products);stopProcessing()}catch(e){stopProcessing();toast(e.message)}}
async function recognizePhoto(file){if(!file)return;startProcessing('Analizuję zdjęcie','Rozpoznaję widoczne produkty…');try{const d=await api('recognize_photo',{},file);if(!d.success)throw new Error(d.message||d.error||'Nie rozpoznano produktów.');setRecognized(d.products);stopProcessing()}catch(e){stopProcessing();toast(e.message)}finally{els.photoInput.value=''}}
async function saveRecognized(){if(!state.recognized.length)return;startProcessing('Dodaję produkty','Zapisuję pozycje na wspólnej liście…');try{const d=await api('add_products',{productsJson:JSON.stringify(state.recognized)});if(!d.success)throw new Error(d.message||d.error||'Nie udało się zapisać produktów.');state.recognized=[];els.textInput.value='';renderRecognized();els.recognitionPanel.classList.add('hidden');await loadList();stopProcessing();toast(`Dodano ${d.added||0} pozycji.`);switchView('list')}catch(e){stopProcessing();toast(e.message)}}
function renderShop(){const checked=state.items.filter(x=>x.checked).length;els.shopItems.innerHTML=state.items.length?state.items.map(x=>`<button class="shop-row ${x.checked?'checked':''}" type="button" data-toggle="${esc(x.itemId)}"><span class="check">${x.checked?'✓':'○'}</span><span><strong>${esc(x.product)}</strong></span></button>`).join(''):'<div class="empty">Lista zakupów jest pusta.</div>';els.finishBtn.disabled=checked===0;els.finishBtn.textContent=checked?`Zakupy zrobione (${checked})`:'Zakupy zrobione'}
async function toggleItem(id){const row=state.items.find(x=>x.itemId===id);if(!row||state.busy)return;startProcessing(row.checked?'Cofam zaznaczenie':'Dodaję do koszyka','Aktualizuję listę…');try{const d=await api('toggle_item',{itemId:id,checked:!row.checked});if(!d.success)throw new Error(d.message||d.error||'Nie udało się zaktualizować produktu.');state.items=Array.isArray(d.items)?d.items:state.items;renderList();renderShop();stopProcessing();if(d.allChecked){await wait(150);await finishShopping('automatic',false)}}catch(e){stopProcessing();toast(e.message)}}
async function finishShopping(mode='manual',ask=true){const checked=state.items.filter(x=>x.checked).length;if(!checked)return;if(ask&&!confirm(`Zakończyć zakupy? Do archiwum trafi ${checked} zaznaczonych pozycji, a bieżąca lista zostanie wyczyszczona.`))return;startProcessing('Kończę zakupy','Zapisuję zakupione produkty w archiwum…');try{const d=await api('finish',{finishMode:mode});if(!d.success)throw new Error(d.message||d.error||'Nie udało się zakończyć zakupów.');state.items=[];renderList();renderShop();stopProcessing();toast('Zakupy zapisane w archiwum.');switchView('archive')}catch(e){stopProcessing();toast(e.message)}}
async function loadArchive(){try{const d=await api('archive');if(!d.success)throw new Error(d.message||d.error||'Nie udało się pobrać archiwum.');state.archive=Array.isArray(d.entries)?d.entries:[];renderArchive()}catch(e){toast(e.message)}}
function renderArchive(){els.archiveDetail.classList.add('hidden');els.archiveItems.innerHTML=state.archive.length?state.archive.map(x=>`<div class="archive-row" data-archive="${esc(x.shoppingId)}"><div><strong>${esc(formatDate(x.completedAt))}</strong><small>${esc(x.finishMode==='automatic'?'zakończone automatycznie':'zakończone ręcznie')}</small></div><span class="badge">${Number(x.itemsCount||0)} poz.</span></div>`).join(''):'<div class="empty">Archiwum jest puste.</div>'}
async function showArchiveDetail(id){startProcessing('Wczytuję zakupy','Pobieram szczegóły archiwum…');try{const d=await api('archive_detail',{shoppingId:id});if(!d.success)throw new Error(d.message||d.error||'Nie znaleziono zakupów.');const e=d.entry||{};const items=Array.isArray(e.items)?e.items:[];els.archiveDetail.innerHTML=`<div class="section-head"><div><h3>${esc(formatDate(e.completedAt))}</h3><p class="muted">${Number(e.itemsCount||items.length)} pozycji</p></div><button class="ghost" type="button" id="closeArchiveDetail">Zamknij</button></div><div class="list">${items.map(x=>`<div class="item"><div class="item-main"><strong>${esc(x.product)}</strong></div></div>`).join('')}</div>`;els.archiveDetail.classList.remove('hidden');stopProcessing();$('closeArchiveDetail')?.addEventListener('click',()=>els.archiveDetail.classList.add('hidden'));els.archiveDetail.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){stopProcessing();toast(e.message)}}
function updateOnline(){els.offline.classList.toggle('show',!navigator.onLine)}
els.tabs.forEach(t=>t.addEventListener('click',()=>switchView(t.dataset.view)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.go)));els.listItems.addEventListener('click',e=>{const b=e.target.closest('[data-delete]');if(b)deleteItem(b.dataset.delete)});els.recognizeTextBtn.addEventListener('click',recognizeText);els.textInput.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')recognizeText()});els.photoInput.addEventListener('change',()=>recognizePhoto(els.photoInput.files?.[0]));els.recognizedItems.addEventListener('click',e=>{const b=e.target.closest('[data-remove-recognized]');if(!b)return;state.recognized.splice(Number(b.dataset.removeRecognized),1);renderRecognized();if(!state.recognized.length)els.recognitionPanel.classList.add('hidden')});els.cancelRecognitionBtn.addEventListener('click',()=>{state.recognized=[];renderRecognized();els.recognitionPanel.classList.add('hidden')});els.saveRecognitionBtn.addEventListener('click',saveRecognized);els.shopItems.addEventListener('click',e=>{const b=e.target.closest('[data-toggle]');if(b)toggleItem(b.dataset.toggle)});els.finishBtn.addEventListener('click',()=>finishShopping('manual',true));els.archiveItems.addEventListener('click',e=>{const r=e.target.closest('[data-archive]');if(r)showArchiveDetail(r.dataset.archive)});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;els.installBtn.classList.remove('hidden')});els.installBtn.addEventListener('click',async()=>{if(!state.installPrompt){toast('W menu przeglądarki wybierz „Zainstaluj aplikację” lub „Dodaj do ekranu głównego”.');return}state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;els.installBtn.classList.add('hidden')});window.addEventListener('appinstalled',()=>{state.installPrompt=null;els.installBtn.classList.add('hidden');toast('Aplikacja została zainstalowana.')});window.addEventListener('online',updateOnline);window.addEventListener('offline',updateOnline);if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});window.addEventListener('load',()=>{updateOnline();loadList()});
